# logic/brand_signature.py

def append_brand_signature(text, lang="ar"):
    signature = "\n\n— تم توليد هذه التوصية بواسطة Sports Sync 🤖" if lang == "ar" else "\n\n— This recommendation was generated by Sports Sync 🤖"
    return text.strip() + signature
